// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SevenThree.Database;

#nullable disable

namespace SevenThree.Database.Migrations
{
    [DbContext(typeof(SevenThreeContext))]
    partial class SevenThreeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SevenThree.Database.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("SevenThree.Database.ApiData", b =>
                {
                    b.Property<int>("ApiDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiDataId"));

                    b.Property<string>("ApiBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.HasKey("ApiDataId");

                    b.ToTable("ApiData");
                });

            modelBuilder.Entity("SevenThree.Database.CallSignAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallSign")
                        .HasColumnType("text");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CallSignAssociation");
                });

            modelBuilder.Entity("SevenThree.Database.Cred", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Pass")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cred");
                });

            modelBuilder.Entity("SevenThree.Database.Figure", b =>
                {
                    b.Property<int>("FigureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FigureId"));

                    b.Property<byte[]>("FigureImage")
                        .HasColumnType("bytea");

                    b.Property<string>("FigureName")
                        .HasColumnType("text");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("FigureId");

                    b.HasIndex("TestId");

                    b.ToTable("Figure");
                });

            modelBuilder.Entity("SevenThree.Database.HamTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TestDescription")
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TestId");

                    b.ToTable("HamTest");
                });

            modelBuilder.Entity("SevenThree.Database.PrefixList", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ServerId"));

                    b.Property<char>("Prefix")
                        .HasColumnType("character(1)");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<long>("SetById")
                        .HasColumnType("bigint");

                    b.HasKey("ServerId");

                    b.ToTable("PrefixList");
                });

            modelBuilder.Entity("SevenThree.Database.Questions", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("FccPart")
                        .HasColumnType("text");

                    b.Property<string>("FigureName")
                        .HasColumnType("text");

                    b.Property<string>("QuestionSection")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("Subelement")
                        .HasColumnType("text");

                    b.Property<string>("SubelementDesc")
                        .HasColumnType("text");

                    b.Property<string>("SubelementName")
                        .HasColumnType("text");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SevenThree.Database.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ServerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("StartedByIconUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("StartedById")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("StartedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeEnded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStarted")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuizId");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("SevenThree.Database.QuizSettings", b =>
                {
                    b.Property<int>("QuizSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizSettingsId"));

                    b.Property<bool>("ClearAfterTaken")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DiscordGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ExtraChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GeneralChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("TechChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("QuizSettingsId");

                    b.ToTable("QuizSettings");
                });

            modelBuilder.Entity("SevenThree.Database.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuizId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("UserAnswer");
                });

            modelBuilder.Entity("SevenThree.Database.Answer", b =>
                {
                    b.HasOne("SevenThree.Database.Questions", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SevenThree.Database.Figure", b =>
                {
                    b.HasOne("SevenThree.Database.HamTest", "Test")
                        .WithMany()
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SevenThree.Database.Questions", b =>
                {
                    b.HasOne("SevenThree.Database.HamTest", "Test")
                        .WithMany()
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SevenThree.Database.UserAnswer", b =>
                {
                    b.HasOne("SevenThree.Database.Questions", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.HasOne("SevenThree.Database.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId");

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
